# Generated by Django 3.2.21 on 2023-10-21 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment_card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=180, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=180, verbose_name='Apellidos')),
                ('phone', models.BigIntegerField(verbose_name='Número de telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('zip_code', models.CharField(max_length=180, verbose_name='Código postal')),
                ('street_address', models.TextField(verbose_name='Dirección de su ubicación')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('gift_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_card.giftcard', verbose_name='Tarjeta de regalo')),
                ('payment_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_card.paymentcard', verbose_name='Método de pago')),
            ],
            options={
                'verbose_name': 'Comprador',
                'verbose_name_plural': 'Compradores',
                'db_table': 'buyers',
            },
        ),
    ]
