# Generated by Django 3.2.21 on 2023-11-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='delivery',
            field=models.BooleanField(default=True, verbose_name='Delivery'),
        ),
    ]
