# Generated by Django 3.2.21 on 2024-09-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_buyer_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='payment_card_status',
            field=models.BooleanField(default=True, verbose_name='Pago por tarjeta Visa'),
        ),
    ]
