# Generated by Django 3.2.21 on 2024-09-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_buyer_payment_card_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='double_buy',
            field=models.BooleanField(default=False, verbose_name='Doble compra de Iphone'),
        ),
    ]
