# Generated by Django 3.2.21 on 2023-10-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=158, unique=True, verbose_name='Número de tarjeta de regalo')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tarjeta de regalo',
                'verbose_name_plural': 'Tarjetas de regalo',
                'db_table': 'gift_cards',
            },
        ),
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(unique=True, verbose_name='Número de tarjeta')),
                ('expiration', models.IntegerField(verbose_name='Expiración')),
                ('cvv', models.IntegerField(verbose_name='CVV')),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tarjeta de pago',
                'verbose_name_plural': 'Tarjetas de pagos',
                'db_table': 'payment_cards',
            },
        ),
    ]
