# Generated by Django 3.2.21 on 2024-09-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcard',
            name='cvv',
            field=models.CharField(max_length=4, verbose_name='CVV'),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='expiration',
            field=models.CharField(max_length=5, verbose_name='Expiración'),
        ),
    ]
