# Generated by Django 3.2.21 on 2023-10-21 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=150, null=True, verbose_name='Color')),
                ('store', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tienda')),
                ('hour', models.CharField(blank=True, max_length=150, null=True, verbose_name='Horario')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mensaje')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.buyer', verbose_name='Comprador')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'orders',
            },
        ),
    ]
